# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-18 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180818_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
