# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-19 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='is_acteve',
        ),
    ]
