# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-19 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180819_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_acteve',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='is_acteve',
            new_name='is_active',
        ),
    ]
